### ISSUE TITLE
i have a problem, i do not understand, can you help me?

### ISSUE THREAD

**Issue by zhengyange** [miguelavaqrod/pptpinosx#1]
```bash
Tue Apr 25 23:42:23 2017 : publish_entry SCDSet() failed: Success!
Tue Apr 25 23:42:23 2017 : publish_entry SCDSet() failed: Success!
Tue Apr 25 23:42:23 2017 : PPTP connecting to server '58.32.252.60' (58.32.252.60)...
Tue Apr 25 23:42:23 2017 : PPTP connection established.
Tue Apr 25 23:42:23 2017 : PPTP set port-mapping for en0, interface: 4, protocol: 0, privatePort: 0
Tue Apr 25 23:42:23 2017 : Using interface ppp0
Tue Apr 25 23:42:23 2017 : Connect: ppp0 <--> socket[34:17]
Tue Apr 25 23:42:23 2017 : PPTP port-mapping for en0, interfaceIndex: 0, Protocol: None, Private Port: 0, Public Address: 644a9dae, Public Port: 0, TTL: 0.
Tue Apr 25 23:42:23 2017 : PPTP port-mapping for en0 inconsistent. is Connected: 1, Previous interface: 4, Current interface 0
Tue Apr 25 23:42:23 2017 : PPTP port-mapping for en0 initialized. is Connected: 1, Previous publicAddress: (0), Current publicAddress 644a9dae
Tue Apr 25 23:42:23 2017 : PPTP port-mapping for en0 fully initialized. Flagging up
Tue Apr 25 23:42:53 2017 : LCP: timeout sending Config-Requests
Tue Apr 25 23:42:53 2017 : Connection terminated.
Tue Apr 25 23:42:53 2017 : PPTP disconnecting...
Tue Apr 25 23:42:53 2017 : PPTP clearing port-mapping for en0
Tue Apr 25 23:42:53 2017 : PPTP disconnected
```

**Comment by miguelavaqrod** [comment]
Hi!

Assuming you have a linux server... I think it might be that your server kernel hasn't got some modules loaded.

Please try this command and try again (on the server...)

sudo modprobe nf_conntrack_pptp

If unlucky... do not hesitate to contact me again.

Regards.

**Comment by zhengyange** [comment]
```bash
sudo pppd call 58.32.252.60

Fri May  5 16:32:39 2017 : publish_entry SCDSet() failed: Success!
Fri May  5 16:32:39 2017 : publish_entry SCDSet() failed: Success!
Fri May  5 16:32:39 2017 : PPTP connecting to server '58.32.252.60' (58.32.252.60)...
Fri May  5 16:32:39 2017 : PPTP connection established.
Fri May  5 16:32:39 2017 : PPTP set port-mapping for en0, interface: 4, protocol: 0, privatePort: 0
Fri May  5 16:32:39 2017 : Using interface ppp0
Fri May  5 16:32:39 2017 : Connect: ppp0 <--> socket[34:17]
Fri May  5 16:32:43 2017 : MPPE 128-bit stateless compression enabled
Fri May  5 16:32:43 2017 : local  IP address 192.168.1.242
Fri May  5 16:32:43 2017 : remote IP address 192.168.1.30
Fri May  5 16:32:43 2017 : Committed PPP store
Fri May  5 16:32:43 2017 : Committed PPP store
Fri May  5 16:32:43 2017 : pptp_wait_input: Address added. previous interface setting (name: en0, address: 192.168.43.16), current interface setting (name: ppp0, family: PPP, address: 192.168.1.242, subnet: 255.255.255.0, destination: 192.168.1.30).
Fri May  5 16:32:43 2017 : PPTP port-mapping for en0, interfaceIndex: 0, Protocol: None, Private Port: 0, Public Address: 0, Public Port: 0, TTL: 0.
Fri May  5 16:32:43 2017 : PPTP port-mapping for en0 inconsistent. is Connected: 1, Previous interface: 4, Current interface 0
```

I think i do it success, 
please pay attention to here:
`Fri May  5 16:32:43 2017 : local  IP address 192.168.1.242
Fri May  5 16:32:43 2017 : remote IP address 192.168.1.30`

I try to connect to `192.168.1.30` by ssh，it is success.
But, but, I want to connect to `192.168.1.110`, so i don't know if there are other configurations
that need to be customized.
Thank you very much!

**Comment by zhengyange** [comment]
I tried to connect to 192.168.1.110, it is failing

**Comment by miguelavaqrod** [comment]
Hi!
Sorry for the delay...

The remote system IP is set on the server side. If Linux, in pptp options (/etc/ppp).
You will just need to change that setting to the desired IP.

Hope it helps...

**Comment by zhengyange** [comment]
@miguelavaqrod 
Sorry, i forgot to tell you, that i used the mac.
And, the mac's version is 'Sierra version 10.12.3'.

**Comment by miguelavaqrod** [comment]
Hi again,

To clarify... are you using a remote mac server where you connect to?
Or your mac is your own device and connect to a remote server (maybe Linux) using this pppd method?

**Comment by zhengyange** [comment]
Yes, you are right, and the mac is mine.
So, what shoud i do?
Thank you.

**Comment by miguelavaqrod** [comment]
Wait.... I think I misunderstood you...

To, again, clarify...
- You connect
- The server (192.168.1.30, in this case) gives your mac a local IP (192.168.1.234)
- You can connect to the server without issues
- And now it is where I misunderstood...
- You want to connect to 192.168.1.110, that IS ANOTHER DEVICE in your remote private network
- Am I right? I suppose that...

In this case, you need to set "forwarding" in your server (using IPTables):

In /etc/rc.local
iptables -t nat -A POSTROUTING -o "interface" -j MASQUERAD (set interface to the corresponding)

In /etc/sysctl.conf:
net.ipv4.ip_forward=1

**Comment by miguelavaqrod** [comment]
Closing as there are no news (no news = good news, hoping he was successful)
